### ISSUE TITLE
Weird SSH screen resolution when bulk connecting 

### ISSUE THREAD

**Issue by I-Fun** [1Remote/1Remote#321]
**Describe the bug**
The Bug is when you Bulk Connect to SSH, the first SSH connection until almost last connection have a weird resolution that not fit the screen

**To Reproduce**
1. Create Multiple SSH Connection
2. Select All the SSH Connection
3. Click Connect
4. you'll see the first connection and the others connection have weird app resolution

**Expected behavior**
it should be had good screen resolution as the last connection of that bulk.

**Screenshots**

![3416---18_13-56-42](https://user-images.githubusercontent.com/7077766/202641159-3457abfb-3951-402b-8160-517ffb2adb8f.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro V21H1
 - PRemoteM Version 0.7.1.7

**Additional context**
i wanna ask something, after we connect with bulk connection and we go to another bulk connection we got new page of bulk connection, is it a bug or it just supposed to be?

**Comment by VShawn** [comment]
# weird app resolution

Thanks for your feedback, sorry for my late respond. Just got through a hard time because of Cov19...

I found `weird app resolution` is not a problem for our operation. In my test, my `ls` shows in a fit resolution:

![image](https://user-images.githubusercontent.com/10143738/207749224-e0f05720-e2b5-47d7-8012-652cea353645.png)

I think `weird app resolution` came from KiTTY init before PRemoteM window init, then KiTTY get a none window size when it print init info. IMO this bug is not a big deal, so I will not fix it immediately :)

# we got new page of bulk connection

I check my logic code, And... Yes it was how I designed. The design looks a little strange at this time I may let them show in the existing window in the feature.
