### ISSUE TITLE
Sortorder in ALT+M Menu

### ISSUE THREAD

**Issue by helmar74** [1Remote/1Remote#359]
**Is your enhancement related to a problem? Please describe.**
Currently the sort order in ALT+M Menu is fixed. The last used connections are shown on 1st place in menu, the fore last on 2nd position and so on.
Current ALT+M Menu:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/25499089/221404963-e31b7468-eb1e-4b11-92e2-ffceef46a06f.png">

**Describe the solution you'd like**
For me it would be great if the sort order could be change with an option or configuration parameter.
It should be possible to sort by connection name. (like it is possible in the main menu)
As I have a lot of connections it would reduce search effort ;-)

**Describe alternatives you've considered**
.

**Additional context**
"New" ALT+M Menü, sorted by connection name:
![image](https://user-images.githubusercontent.com/25499089/221405231-b71d9644-c89a-41c7-9bcc-0ec7dd7a96a4.png)

**Comment by helmar74** [comment]
> 

That would be fine for me. But maybe you can also make it "configurable"?
![image](https://user-images.githubusercontent.com/25499089/222334202-3f81e867-3f54-4013-8397-ca902dd8fc74.png)

**Comment by VShawn** [comment]
I think twice and find it weird if I order items by name in the launcher.

Since items are already sort by name in the main window view, a name order launcher looks meaningless...

**Comment by helmar74** [comment]
OK, but it would make it easier to find in the launcher...
For me it's quicker to find a connection just scrolling down the list instead of  typing in launcher.

**Comment by helmar74** [comment]
Great, thank you so much!
In which version will it be active?

**Comment by VShawn** [comment]
well, this ticket will not be achieved since it was moved into 'Limbo'

**Comment by VShawn** [comment]
if you strongly expect this feature, you can build a own version by fork this project and remove the order method in the launched：

in LauncherWindowViewModel.cs

around line 390, remove the statement `.OrderByDescending(x => x.Server.LastConnTime)` in code below.

``` C#
                Execute.OnUIThread(() =>
                {
                    VmServerList = new ObservableCollection<ProtocolBaseViewModel>(newList.OrderByDescending(x => x.Server.LastConnTime));
                });
```

edit and commit the change, then github action will help you build a new release packge for you.

Quite easy hum :)

Since you don't need Quite easy

**Comment by helmar74** [comment]
> well, this ticket will not be achieved since it was moved into 'Limbo'

Sorry for the question, but what das "Limbo" mean?

**Comment by majkinetor** [comment]
Limbo is the place where some request/ideas live. They generally have merit but its not certain if they are going to get implemented due to complexity, other more important ideas etc. So they are in levitating in limbo for the time being. From there, they can go to Next or closed as in no, we are not going to do that, based on discussion.

**Comment by VShawn** [comment]
Oh sorry for forgot to reply this one.
