### ISSUE TITLE
Add character set translation option to Kitty 

### ISSUE THREAD

**Issue by luckykeeper** [1Remote/1Remote#436]
[Feature request] (Kitty) Add Translation Option | 【功能建议】(Kitty)增加字符集转换选项

Putty/Kitty 支持字符集转换选项，能够选择字符集，希望能在设置里面增加这一选项以适应个别中文设备（如华为）

如下图所示：华为设备需要选择“使用字体编码才能支持中文显示”，而当前并不支持设置这一功能，putty是原生支持的，希望能够添加这一选项，感谢！

截图设备：华为 SmartAX MA5698

![image](https://github.com/1Remote/1Remote/assets/34579433/61aec425-9b15-47f6-be7b-24f50bf1e0c8)

![image](https://github.com/1Remote/1Remote/assets/34579433/e8e53351-50ab-4a81-af1f-e82a89482665)

![image](https://github.com/1Remote/1Remote/assets/34579433/2d76806f-db39-4be4-adf2-c4c184327b2a)

**Comment by VShawn** [comment]
For now I'm not sure if we can set this `character set` by CLI when start SSH connection. I will find out in the kitty document and test it latter.

**Comment by luckykeeper** [comment]
> For now I'm not sure if we can set this `character set` by CLI when start SSH connection. I will find out in the kitty document and test it latter.

Thanks a lot, looking forward to the update👍

**Comment by VShawn** [comment]
Hi @luckykeeper 

Here's the solution:

1. create a txt somewhere with content `LineCodePage\Use%20font%20encoding\`
2. conif the KiTTY Session of your ssh connection.

![image](https://github.com/1Remote/1Remote/assets/10143738/f922a0ca-f1ed-4f86-8d27-e29c8fda9017)

then your KiTTY session character set will be set to `Use font encoding`.

Plz test by yourself since I don't have any HUAWEI device, UTF-8 works fine with my PC :)

**Comment by luckykeeper** [comment]
It works! Thanks a lot!

![image](https://github.com/1Remote/1Remote/assets/34579433/b4bb7783-0563-448c-a0bc-a3d781d724ef)


I'll close this issue
