### ISSUE TITLE
Wake On Lan Feature

### ISSUE THREAD

**Issue by Gameniti** [1Remote/1Remote#448]
**Is your feature request related to a problem? Please describe.**
Based on #447 

**Describe the solution you'd like**
A built-in way to send a magic packet. Assigning a MAC-Address to a connection and either being able to manually send a WOL package with a button and/or automatically do it when trying to connect to an offline machine.

For the latter, it could be necessary to add a delay to the connection while the machine boots up.

**Comment by VShawn** [comment]
according to #352

As WOL is rarely used, I defined it as a script feature that users can implement on their own. 

You can ping the server and attempt WOL within the script: If the server is offline, you can set a sleep duration in the script after wol package is sent. After your WOL script concludes, 1RM will then establish the remote connection.

Personally, I don't wish to integrate WOL into 1RM, especially since the 1RM already supports multiple remote addresses for a single server. Supporting WOL would require storing multiple MAC addresses for different network address, which would introduce additional complexity to the app and potentially result in more bugs.

**Comment by majkinetor** [comment]
There is already discussion about it  https://github.com/1Remote/1Remote/discussions/365 so I will close this. I edit the answers to keep it all there.
