### ISSUE TITLE
When using mstsc mode script after disconnected not working

### ISSUE THREAD

**Issue by andy1463** [1Remote/1Remote#471]
Hello,
if a script for running after disconnecting a RDP connection is configured it will be not executed if option mstsc.exe mode is enabled.
Same configuration only removing mstsc.exe mode and the script will be executed.

Tested on Windows 10 Pro (21H2)

**Comment by VShawn** [comment]
This is indeed a missed point. 

but technically, there is no connection between the mstsc process and 1remote mstsc mode is activated, so `script after disconnected not working`. In order to achieve this, we would need a process monitor, but we are unsure if it will trigger the defense rules of antivirus software.

**Comment by majkinetor** [comment]
Monitoring started process is normal thing.

**Comment by VShawn** [comment]
I fixed it
