### ISSUE TITLE
Can't maximize or fullscreen the window when use xrdp as RDP server

### ISSUE THREAD

**Issue by toadouyang** [1Remote/1Remote#503]
**Describe the bug**
Can't maximize or fullscreen the window when use xrdp as RDP server.
Another problem, when use mstsc as client, if you have a connection exsit, a new connection will cause the old connection disconnected, but use 1Remote, this will keep the two connection at same time

**To Reproduce**
1. use 1Remote connect to RDP server serviced by xrdp(https://github.com/neutrinolabs/xrdp)
2. The connection will open a very small window and have no maximize or fullscreen button 

**Expected behavior**
We expect that it have maximize or fullscreen buttom

**Screenshots**
![image](https://github.com/1Remote/1Remote/assets/5219250/5e824f09-6b21-4d59-9ce6-0fab92326ecb)

**Desktop (please complete the following information):**
 - OS: win11/winserver 2022
 - PRemoteM Version :1.0.0-beta.06

**Comment by VShawn** [comment]
This could be a bug, or it might not be, because when I tested it using mstsc.exe, the maximize button didn't work. When I clicked the button, the window remained in its current size. 

I suggest using the mstsc mode in 1Remote until I find the cause of the problem. 

P.S. I've never used a Linux desktop version before, so if you have any suggestions for using xrdp, please let me know.

![image](https://github.com/1Remote/1Remote/assets/10143738/c66d4d6c-f040-4791-8a5d-2447a66b3241)
