### ISSUE TITLE
RDP mode: CTRL+ALT+LEFT/RIGHT didn't translate to remote

### ISSUE THREAD

**Issue by lanmaster** [1Remote/1Remote#511]
Running on Windows 10. Remote RDP is Windows 10 too.
Is it possible to send CTRL+ALT+LEFT/RIGHT shortcuts to remote RDP ?

**Comment by lanmaster** [comment]
This combination is used by default in Intellij IDEA

**Comment by VShawn** [comment]
we can sent ctrl + win + ... but can not send ctrl + alt + ... BY the limit of the mstsc.dll / mstsc.exe.

Microsoft made another version of RDP, and `ctrl + alt + ...` seems can be send on it. but unfortunately we are not able to use this version since Microsoft does not offering the dll of this version to us.

you can learn more from https://superuser.com/questions/327866/remote-desktop-sending-ctrl-alt-left-arrow-ctrl-alt-right-arrow-to-the-remote-p
