### ISSUE TITLE
Kitty integration

### ISSUE THREAD

**Issue by tj57** [1Remote/1Remote#627]
What do you think about direct integration of kitty, so as to add another tab and run the kitty window inside the 1Remote window ?

Kitty has a lot of configuration options, ssh tunnels, X11 forwarding etc.

Like on this screeen ?
![image](https://github.com/1Remote/1Remote/assets/20434907/93091c43-5c30-43ef-985e-45ae91ff840d)

![image](https://github.com/1Remote/1Remote/assets/20434907/36758825-8c0e-4e4e-bbc3-6f396c0c3f8d)

Another option is to autoimport files directly from Sessions with Kitty, only then you won't be able to edit them in 1Remote.
Create config file directly in kitty, autoimport to 1Remote and call it

**Comment by VShawn** [comment]
> Kitty has a lot of configuration options, ssh tunnels, X11 forwarding etc.
> Like on this screeen ?

Because Kitty's configuration window and terminal window are two different windows, their HWNDs are different. Currently, 1Remote can only capture one HWND when integrating third-party programs, so itis difficult to achieve. At least I think the effort does not match the return. If that's the case, I would rather use KITTY's UI directly instead of the integrated one. Telemetry data also supports this view,  with only a very small number of people using the 1Remote `import kitty session` feature.

> Create config file directly in kitty, autoimport to 1Remote and call it

We can now import the kitty session but lack for auto import. 

The reason we lack the ability to auto import session is that we do not know where to auto import the session files from. Users may use both the portable and non-portable versions of kitty, and the storage path of the session cannot be anticipated.

**Comment by tj57** [comment]
> > Kitty has a lot of configuration options, ssh tunnels, X11 forwarding etc.
> > Like on this screeen ?
> 
> Because Kitty's configuration window and terminal window are two different windows, their HWNDs are different. Currently, 1Remote can only capture one HWND when integrating third-party programs, so itis difficult to achieve. At least I think the effort does not match the return. If that's the case, I would rather use KITTY's UI directly instead of the integrated one. Telemetry data also supports this view, with only a very small number of people using the 1Remote `import kitty session` feature.

If you're interested, I have an older version of PRemotem converted by a friend with added Kitty portable support and capture of both windows. I don't know much about C#, but I can make it available.

> 
> > Create config file directly in kitty, autoimport to 1Remote and call it
> 
> We can now import the kitty session but lack for auto import.
> 
> The reason we lack the ability to auto import session is that we do not know where to auto import the session files from. Users may use both the portable and non-portable versions of kitty, and the storage path of the session cannot be anticipated.

Set retriction, if only one mode of import is available?
Import is avaliable only from selected directory and Sessions portable mode.

**Comment by VShawn** [comment]
> If you're interested, I have an older version of PRemotem converted by a friend with added Kitty portable support and capture of both windows. I don't know much about C#, but I can make it available.

Of course, I am happy to refer to any third-party implementations.

Oh, by the way, due to my scenario, I have never used SSH tunnels, X11 forwarding functions. so I am not familiar with their principles, which is also a barrier to me adding new SSH features.
