### ISSUE TITLE
Exiting full screen mode (windows 10 2 terminals)?

### ISSUE THREAD

**Issue by rafi-d** [1Remote/1Remote#632]
From time to time, after some time,  the full screen mode top banner - is NOT showing up any mode... I guess it is a bug...

A simple question: what key is used to exit full screen?

**Comment by majkinetor** [comment]
https://learn.microsoft.com/en-us/windows/win32/termserv/terminal-services-shortcut-keys?redirectedfrom=MSDN

**Comment by rafi-d** [comment]
PS:
You might want o add this link in your documentation - page too :) ...
Just to note - that I was using Microsoft own Remote Desktop app (from the store) for years, without this banner issue...

**Comment by VShawn** [comment]
I noticed that the conn bar disappears in full screen mode with multiple monitors long ago. And everything works fine with a single monitor. So it might because some tricks introduced to make full screen mode with multiple monitors works, leading to this bar issue. 

For now, I have to compromise with the issue of the conn bar to make screen mode work.
