### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by KeithW-JBTC** [1Remote/1Remote#674]
**Describe the bug**
Unexpected error occured.

**To Reproduce**
1. Launch 1Remote
2. See error

**Expected behavior**
Application runs normally.

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - 1Remote Version 1.0.0-beta.07

**Additional context**
[1Remote Error details.txt](https://github.com/user-attachments/files/15603342/1Remote.Error.details.txt)

**Comment by VShawn** [comment]
The log indicates that Accessibility.dll cannot be found.

I'm sorry that I don't know how this happened, so I went to stackoverflow to seek solutions and found that multiple threads suggested that the issue might be caused by system file corruption:

https://stackoverflow.com/questions/58481483/could-not-load-file-or-assembly-accessibility-version-4-0-0-0

https://stackoverflow.com/questions/5859389/system-io-fileloadexception-could-not-load-accessibility-version-2-0-0-0

I suggest you can follow the advice on stackoverflow to try reinstalling the .NET environment, or place the DLL I uploaded into the folder of 1Remote.exe.

[Accessibility.zip](https://github.com/user-attachments/files/15687899/Accessibility.zip)
