### ISSUE TITLE
cant open existing 1remote mysql db from running in visual studio

### ISSUE THREAD

**Issue by chuckgmthompson** [1Remote/1Remote#748]
I installed 1remote on one computer.  connected to a mysql instance, and imported a bunch of connections.  works fine on that installed version.  on another machine I open the source code and connect to that same mysql db and I get an error:

 your database is encrypted by a third-part build 1Remote_Debug, this app can not read your data correctly

I then installed 1Remote on yet another machine and connect to that mysql and see everything fine.
It just seems to be an issue if connecting from a debug environment.
Any suggestions?

**Comment by VShawn** [comment]
The issue you're experiencing is due to the version on GitHub being built with a random encryption salt , which is generated on the GitHub action server. This means that any databases created by the official release cannot be read correctly by local development builds.

If you would like to use a locally compiled version, here's the solution: 

use the official release exe to export existing data, then import them using your own compiled version. Additionally, ensure that all machines are running the same locally compiled version for compatibility.

Let us know if you have any further questions!
