### ISSUE TITLE
Feature Request: Add Folders (and subfolders) as RDM Devolution, import from Json RDM Devolution and Browser navigation

### ISSUE THREAD

**Issue by sql99** [1Remote/1Remote#749]
Add Folders (and subfolders) as RDM Devolution and import from Json RDM Devolution and Browser navigation to Vcenter or Proxmox (for example)

**Comment by majkinetor** [comment]
We could make tag have parents so they can behave like folders.... just sayin', I still think flat structure is enough.

**Comment by sql99** [comment]
If you think that  flat structure is enough. this software is not adapt for many connection of several customers

**Comment by sql99** [comment]
@VShawn  Why do you want use only tag, i want have the freedom of choose I which method is more adpat for me.

**Comment by VShawn** [comment]
simply because tag is enough for me, and I don't have much time to turn tag based system into folder based system. If you really need this feature, forks and pull requests are very welcome.

> If you think that flat structure is enough. this software is not adapt for many connection of several customers

Yes you got the point, the app is designed for personal use, as its old name `PRemoteM` -> `personal remote manager` :)
