### ISSUE TITLE
Crash when switching tabs

### ISSUE THREAD

**Issue by itagagaki** [1Remote/1Remote#773]
Steps to reproduce:
1. Open an RDP session
2. Open a Serial session (The serial tab becomes active)
3. Click the RDP tab

The error info is attached.
[errorinfo2024-11-14-23.16.42.md](https://github.com/user-attachments/files/17749863/errorinfo2024-11-14-23.16.42.md)

**Comment by itagagaki** [comment]
Opening a single RDP session and clicking on that tab crashed in the same way. So it may not be a session switching issue, but simply a tab click event handler issue.

**Comment by itagagaki** [comment]
This commit seems to be the culprit: 060dc7adbbd02a98253498fc2aa1ebd7d822b38a

**Comment by VShawn** [comment]
`Object reference not set to an instance of an object.`

从遥测系统中我有时会看到这个错误报告，错误显然来源于 Dragablz 控件。由于直接引用 nuget 包看不到错误信息，并且Dragablz 已经多年没有维护了，于是才有了这个 commit：https://github.com/1Remote/1Remote/commit/060dc7adbbd02a98253498fc2aa1ebd7d822b38a，通过 fork Dragablz 来 让错误日志显示出错误行号。

rom the telemetry system, I got this error report from time to time, which clearly originates from the Dragablz control. Since directly referencing the NuGet package doesn't show the error details and Dragablz has not been maintained for years, I made the commit: https://github.com/1Remote/1Remote/commit/060dc7adbbd02a98253498fc2aa1ebd7d822b38a, by forking Dragablz to allow the error log to display the line number of the issue in the nightly built.

**Comment by VShawn** [comment]
I found that the referenced Dragablz branch(https://github.com/BornToBeRoot/Dragablz) introduced new bug while fixing those old ones.
