### ISSUE TITLE
Icon selector improvement.

### ISSUE THREAD

**Issue by itagagaki** [1Remote/1Remote#779]
In here:

![image](https://github.com/user-attachments/assets/fd2dd842-f8d2-4256-bf0f-0f2d191ca41e)

I think that [**Choose File...**] [**OK**] [**Cancel**] is better than [Upload] [Done] [Reset].

Also, the terms "logo" and "icon" seem to be used interchangeably. I think the term should be unified with "icon".
Or, at least, it's better to correct "Show current session icon instead of app icon when connected" to "Show current session _logo_ instead of app icon when connected".

**Comment by majkinetor** [comment]
This always confuses me, its bad UX.

IMO, it should work this way:

1. 'Icon' always instead of logo
2. Remove all 3 buttons 
    1. Clicking the icon should open the icon browser
    2. Current icon should be selected, and you can select another one
3. Icon is saved when you save connection settings. If you want to reset it, cancel settings.

"Uploading", e.g. selecting local icon which is then copied to internal 1RM folder should be redone differently as current option is not very flexible.

**Comment by VShawn** [comment]
much better now


https://github.com/user-attachments/assets/b1ea1f43-eef5-47fb-9555-432891823a51

**Comment by itagagaki** [comment]
Very good! I don't think we need the ‘Upload’ heading anymore.

**Comment by VShawn** [comment]
I hesitate if users know they can click the icon to upload images without a title

**Comment by VShawn** [comment]
looks good
